name: run test
on: [push, pull_request]
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@main

      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 29.4

      - name: Install dependend packages
        run: make deps

      - name: Run tests
        run: make test
